# Spring配置
spring:
  # 数据源配置
  datasource:
    # MySQL数据库连接URL，指定了数据库为rpsm，使用Unicode编码，UTF-8字符集，UTC时区
    url: jdbc:mysql://localhost:3306/rpsm?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    # 数据库用户名
    username: root
    # 数据库密码
    password: 123456

# MyBatis配置
mybatis:
  # Mapper XML文件的位置，位于classpath下的mapper目录
  mapper-locations: classpath:mapper/*.xml
  # MyBatis配置项
  configuration:
    # 使用标准输出实现日志打印，方便调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名转换，将数据库中的下划线命名转换为Java中的驼峰命名
    map-underscore-to-camel-case: true

# PageHelper分页插件配置
pagehelper:
  # 指定数据库方言为MySQL
  helper-dialect: mysql
  # 启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  reasonable: true
  # 支持通过Mapper接口参数传递分页参数
  support-methods-arguments: true
  # 设置count参数名为countSql
  params: count=countSql

# SpringDoc Swagger配置
springdoc:
  # Swagger UI配置
  swagger-ui:
    # 按字母顺序排序标签
    tagsSorter: alpha
    # 按字母顺序排序操作
    operationsSorter: alpha
    # 默认模型展开深度设置为-1，不显示模型
    defaultModelsExpandDepth: -1

# 服务器配置
server:
  # 服务器端口号设置为8081
  port: 8081
