#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url:
#  jdbc:mysql://localhost:3306/mysql?userUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#  username:root
#  password:123456
#  database:MYSQL
#mybatis:
#  mapper-locations:/mapper/*.xml
#  configuration:
#    log-impl:org.apache.ibatis.logging.stdout.StdOutIml